### ISSUE TITLE
Missing def _get_neighbor_triple_sets

### ISSUE THREAD

**Issue by AdamSwift95** [hu-dske/CKGAT#3]
Hello, 

There seems to be part of the code missing:

Traceback (most recent call last):
  File "/home/a_k_swift/Documents/thesis/Recc/recommenders/rec_thesis/models/CKGAT/src/main.py", line 40, in <module>
    data_info = load_data(args)
  File "/home/a_k_swift/Documents/thesis/Recc/recommenders/rec_thesis/models/CKGAT/src/data_loader.py", line 14, in load_data
    user_triple_sets, user_neighbor_triple_sets = kg_propagation(args, kg, user_init_entity_set,
  File "/home/a_k_swift/Documents/thesis/Recc/recommenders/rec_thesis/models/CKGAT/src/data_loader.py", line 151, in kg_propagation
    _get_neighbor_triple_sets(args.neighbor_size, all_h, all_r, all_t, indices)) 
NameError: name '_get_neighbor_triple_sets' is not defined

**Comment by duanchao** [comment]
你好 这个方法找到了吗
